apiVersion: neotoma v2.0
headers: 2
kind: Development
metadata:
- column: datasettypeid
  neotoma: ndb.datasettypes.datasettype
  overwrite: false
  required: true
  value: pollen
- column: databaseid
  neotoma: ndb.datasetdatabases.databasename
  overwrite: false
  required: true
  value: African Pollen Database
- column: Address
  neotoma: ndb.contacts.address
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Age
  neotoma: ndb.chroncontrols.age
  notes: here only if part of chronology?
  overwrite: false
  required: false
  rowwise: false
  type: float
- column: Age
  neotoma: ndb.chronologies.age
  notes: here only if part of chronology?
  overwrite: false
  required: false
  rowwise: true
  type: float
- column: Age
  neotoma: ndb.geochronology.age
  notes: should i put this here?
  overwrite: false
  required: false
  rowwise: false
  type: float
- column: AgeBoundOlder
  neotoma: ndb.chronologies.ageboundolder
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: AgeBoundYounger
  neotoma: ndb.chronologies.ageboundyounger
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: AgeModelNotes
  neotoma: ndb.chronologies.notes
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: AgeUnits
  neotoma: ndb.chronologies.agetype
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: AgeUnits_Sample
  neotoma: ndb.chroncontrols.agetype
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: AgeUnits_Sample
  neotoma: ndb.sampleages.agetype
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: Altitude
  neotoma: ndb.sites.altitude
  overwrite: false
  required: false
  rowwise: false
  type: float
- column: Anal.Thick
  neotoma: ndb.analysisunits.thickness
  overwrite: false
  required: false
  rowwise: true
  type: float
- column: Area
  neotoma: ndb.sites.area
  overwrite: false
  required: false
  rowwise: false
  type: float
- column: CUNotes
  neotoma: ndb.collectionunits.notes
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: ChronologyName
  neotoma: ndb.chronologies.chronologyname
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Citation
  neotoma: ndb.publications.citation
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: CollectionDate
  neotoma: ndb.collectionunits.colldate
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: CollectionDevice
  neotoma: ndb.collectionunits.colldevice
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: CollectionName
  neotoma: ndb.collectionunits.collunitname
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: CollectionType
  neotoma: ndb.collectionunits.colltypeid
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Collectors_ID
  neotoma: ndb.collectors.contactid
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: ContactTitle
  neotoma: ndb.contacts.title
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Country
  neotoma: ndb.sitegeopolitical.geopoliticalunit1
  notes: double check these fields
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: County
  neotoma: ndb.sitegeopolitical.geopoliticalunit3
  notes: double check these fields
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: DOI_pub
  neotoma: ndb.publications.doi
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: DatasetType
  neotoma: ndb.datasets.datasettype
  overwrite: false
  required: true
  rowwise: false
  type: string
- column: DatePrepared
  neotoma: ndb.chronologies.dateprepared
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: Default
  neotoma: ndb.chronologies.isdefault
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: DepositionalEnvironment
  neotoma: ndb.collectionunits.depenvtid
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Depth
  neotoma: ndb.chroncontrols.depth
  overwrite: false
  required: false
  rowwise: false
  type: float
- column: Email
  neotoma: ndb.contacts.email
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: ErrorOlder
  neotoma: ndb.sampleages.uncertainty
  overwrite: false
  required: false
  rowwise: true
  type: float
- column: ErrorYounger
  neotoma: ndb.geochronology.erroryounger
  overwrite: false
  required: false
  rowwise: false
  type: float
- column: OlderSampleAge
  neotoma: ndb.sampleages.ageolder
  overwrite: false
  required: false
  rowwise: true
  type: float
- column: YoungerSampleAge
  neotoma: ndb.sampleages.ageyounger
  overwrite: false
  required: false
  rowwise: true
  type: float
- column: FamilyName
  neotoma: ndb.contacts.familyname
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Fax
  neotoma: ndb.contacts.fax
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: FullContactName
  neotoma: ndb.contacts.contactname
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: GPSAltitude
  neotoma: ndb.collectionunits.gpsaltitude
  overwrite: false
  required: false
  rowwise: false
  type: float
- column: GPSError
  neotoma: ndb.collectionunits.gpserror
  overwrite: false
  required: false
  rowwise: false
  type: float
- column: GPSLat
  neotoma: ndb.collectionunits.geog.latitude
  overwrite: false
  required: true
  rowwise: false
  type: float
- column: GPSLong
  neotoma: ndb.collectionunits.geog.longitude
  overwrite: false
  required: true
  rowwise: false
  type: float
- column: GivenNames
  neotoma: ndb.contacts.givennames
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Handle
  neotoma: ndb.collectionunits.handle
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Investigators_ID
  neotoma: ndb.datasetpis.contactid
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Investigators_geochron_neoID
  neotoma: ndb.chronologies.contactid
  notes: ??
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Journal
  neotoma: ndb.publications.journal
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: LabNumber
  neotoma: ndb.geochronology.labnumber
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: LatNorth
  neotoma: ndb.sites.geog.latitude
  overwrite: false
  required: true
  rowwise: false
  type: float
#- column: LatSouth
#  neotoma: ndb.sites.latitudesouth
#  notes: null
#  overwrite: false
#  required: false
#  rowwise: 0.0
#  type: float
- column: LeadingInitials
  neotoma: ndb.contacts.leadinginitials
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Location
  neotoma: ndb.collectionunits.location
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: LongEast
  neotoma: ndb.sites.geog.longitude
  overwrite: false
  required: true
  rowwise: false
  type: float
#- column: LongWest
#  neotoma: ndb.sites.longitudewest
#  notes: null
#  overwrite: false
#  required: false
#  rowwise: 0.0
#  type: float
- column: MaterialDated
  neotoma: ndb.geochronology.materialdated
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Method
  neotoma: ndb.geochronology.geochrontypeid
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Model
  neotoma: ndb.chronologies.agemodel
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Model
  neotoma: ndb.sampleages.agemodel
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: SampleAge
  neotoma: ndb.sampleages.age
  overwrite: false
  required: false
  rowwise: true
  type: float
- column: Name
  neotoma: ndb.datasets.datasetname
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: NeotomaAliasID
  neotoma: ndb.contacts.contactid
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: NeotomaContactID
  neotoma: ndb.contacts.contactid
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: NeotomaID_pub
  neotoma: ndb.publications.publicationid
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Pages
  neotoma: ndb.publications.pages
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: PreparersContactID_neo
  neotoma: ndb.chronologies.contactid
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: Processors_ID
  neotoma: ndb.datasetprocessor.contactid
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: PublicationType
  neotoma: ndb.publications.pubtypeid
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: PublicationYear
  neotoma: ndb.publications.year
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: SampleAge
  neotoma: ndb.chroncontrols.age
  overwrite: false
  required: false
  rowwise: false
  type: float
- column: SampleNotes
  neotoma: ndb.geochronology.notes
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: SiteDescription
  neotoma: ndb.sites.sitedescription
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: SiteID
  neotoma: ndb.sites.siteid
  overwrite: false
  required: true
  rowwise: false
  type: int
- column: collunitid
  neotoma: ndb.collectionunits.collectionunitid
  overwrite: false
  required: true
  rowwise: false
  type: int
- column: SiteName
  neotoma: ndb.sites.sitename
  overwrite: false
  required: true
  rowwise: false
  type: string
- column: SiteNotes
  neotoma: ndb.sites.notes
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: SlopeAngle
  neotoma: ndb.collectionunits.slopeangle
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: SlopeAspect
  neotoma: ndb.collectionunits.slopeaspect
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: State
  neotoma: ndb.sitegeopolitical.geopoliticalunit2
  notes: double check these fields
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Substrate
  neotoma: ndb.collectionunits.substrateid
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Telephone
  neotoma: ndb.contacts.phone
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Thickness
  neotoma: ndb.chroncontrols.thickness
  overwrite: false
  required: false
  rowwise: false
  type: float
- column: Title
  neotoma: ndb.publications.articletitle
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: URL
  neotoma: ndb.contacts.url
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Volume
  neotoma: ndb.publications.volume
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: WaterDepth
  neotoma: ndb.collectionunits.waterdepth
  overwrite: false
  required: false
  rowwise: false
  type: float
- column: analysisunitname
  neotoma: ndb.analysisunits.analysisunitname
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: authorIDs
  neotoma: ndb.publicationauthors.contactid
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: depths
  neotoma: ndb.analysisunits.depth
  overwrite: false
  required: false
  rowwise: true
  type: float
- column: element
  neotoma: ndb.variables.variableelement
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: value
  neotoma: ndb.data.value
  overwrite: false
  required: false
  rowwise: true
  type: int
- column: variablename
  neotoma: ndb.variables.taxon
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: SampAnalyst_neoID
  neotoma: ndb.sampleanalysts.contactid
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: Samp.Analyst
  neotoma: ndb.sampleanalysts.contactname
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: Processors_Name
  neotoma: ndb.dataprocessors.contactname
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: Collectors_Names
  neotoma: ndb.collectors.contactname
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: Preparers_Name
  neotoma: ndb.chronologies.contactname
  overwrite: false
  required: false
  rowwise: true
  type: string
- column: Investigators_Names
  neotoma: ndb.datasetpis.contactname
  overwrite: false
  required: false
  rowwise: false
  type: string
- column: units
  neotoma: ndb.variables.variableunits
  overwrite: false
  required: false
  rowwise: true
  type: string
