apiVersion: neotoma v2.0
headers: 2
kind: Development
metadata:
- column: DatasetType
  neotoma: ndb.datasettypes.datasettypeid
  required: true
  value: pollen
- column: databaseid
  neotoma: 'ndb.datasetdatabases.databasename'
  required: true
  value: African Pollen Database
- column: depths
  neotoma: ndb.analysisunits.depth
  notes:
  required:
  rowwise: true
  type: float
- column: Anal.Thick
  neotoma: ndb.analysisunits.thickness
  notes:
  required:
  rowwise: true
  type: float
- column: Age
  neotoma: ndb.sampleages.age
  notes:
  required:
  rowwise: true
  type: float
  chronologyname: Temoltzin-Loranca et al. (2023)
- column: value_Sample.quantity_1
  neotoma: ndb.data.value
  notes:
  required:
  rowwise: true
  taxonname: Sample quantity
  type: float
- column: value_Lycopodium.tablets_1
  neotoma: ndb.data.value
  notes:
  required:
  rowwise: true
  taxonname: Lycopodium tablets
  type: float
- column: value_Lycopodium.tablets_2
  neotoma: ndb.data.value
  notes:
  required:
  rowwise: true
  taxonname: Lycopodium tablets
  type: float
- column: value_Lycopodium.spike_1
  neotoma: ndb.data.value
  notes:
  required:
  rowwise: true
  taxonname: Lycopodium spike
  type: float
- column: value_Alternanthera_1
  neotoma: ndb.data.value
  notes:
  required:
  rowwise: true
  taxonname: Alternanthera
  type: float
- column: value_Anthoceros.laevis.type_1
  neotoma: ndb.data.value
  notes:
  required:
  rowwise: true
  taxonname: Anthoceros laevis-type
  type: float
- column: value_Basella_1
  neotoma: ndb.data.value
  notes:
  required:
  rowwise: true
  taxonname: Basella
  type: float
- column: units_Sample.quantity_1
  neotoma: ndb.variables.variableunitsid
  notes:
  required:
  rowwise: true
  taxonname: Sample quantity
  type: string
- column: units_Lycopodium.tablets_1
  neotoma: ndb.variables.variableunitsid
  notes:
  required:
  rowwise: true
  taxonname: Lycopodium tablets
  type: string
- column: units_Lycopodium.tablets_2
  neotoma: ndb.variables.variableunitsid
  notes:
  required:
  rowwise: true
  taxonname: Lycopodium tablets
  type: string
- column: units_Lycopodium.spike_1
  neotoma: ndb.variables.variableunitsid
  notes:
  required:
  rowwise: true
  taxonname: Lycopodium spike
  type: string
- column: units_Alternanthera_1
  neotoma: ndb.variables.variableunitsid
  notes:
  required:
  rowwise: true
  taxonname: Alternanthera
  type: string
- column: units_Anthoceros.laevis.type_1
  neotoma: ndb.variables.variableunitsid
  notes:
  required:
  rowwise: true
  taxonname: Anthoceros laevis-type
  type: string
- column: units_Basella_1
  neotoma: ndb.variables.variableunitsid
  notes:
  required:
  rowwise: true
  taxonname: Basella
  type: string
- column: element_Lycopodium.tablets_1
  neotoma: ndb.variables.variableelementid
  notes:
  required:
  rowwise: true
  taxonname: Lycopodium tablets
  type: string
- column: element_Lycopodium.tablets_2
  neotoma: ndb.variables.variableelementid
  notes:
  required:
  rowwise: true
  taxonname: Lycopodium tablets
  type: string
- column: element_Lycopodium.spike_1
  neotoma: ndb.variables.variableelementid
  notes:
  required:
  rowwise: true
  taxonname: Lycopodium spike
  type: string
- column: element_Alternanthera_1
  neotoma: ndb.variables.variableelementid
  notes:
  required:
  rowwise: true
  taxonname: Alternanthera
  type: string
- column: element_Anthoceros.laevis.type_1
  neotoma: ndb.variables.variableelementid
  notes:
  required:
  rowwise: true
  taxonname: Anthoceros laevis-type
  type: string
- column: element_Basella_1
  neotoma: ndb.variables.variableelementid
  notes:
  required:
  rowwise: true
  taxonname: Basella
  type: string
  type: string
- column: SiteName
  neotoma: ndb.sites.sitename
  notes:
  required:
  rowwise: no
  type: string
- column: SiteID
  neotoma: ndb.sites.siteid
  notes:
  required:
  rowwise: no
  type: int
- column: LongEast
  neotoma: ndb.sites.geog.longitude
  notes:
  required:
  rowwise: no
  type: float
- column: LatNorth
  neotoma: ndb.sites.geog.latitude
  notes:
  required:
  rowwise: no
  type: float
- column: Altitude
  neotoma: ndb.sites.altitude
  notes:
  required:
  rowwise: no
  type: float
- column: Area
  neotoma: ndb.sites.area
  notes:
  required:
  rowwise: no
  type: float
- column: Country
  neotoma: ndb.sitegeopolitical.national_unit
  notes:
  required:
  rowwise: no
  type: string
- column: State
  neotoma: ndb.sitegeopolitical.subnational_unit_lv1
  notes:
  required:
  rowwise: no
  type: string
- column: County
  neotoma: ndb.sitegeopolitical.subnational_unit_lv2
  notes:
  required:
  rowwise: no
  type: string
- column: SiteDescription
  neotoma: ndb.sites.sitedescription
  notes:
  required:
  rowwise: no
  type: string
- column: SiteNotes
  neotoma: ndb.sites.notes
  notes:
  required:
  rowwise: no
  type: string
- column: Handle
  neotoma: ndb.collectionunits.handle
  notes:
  required:
  rowwise: no
  type: string
- column: CollectionName
  neotoma: ndb.collectionunits.collunitname
  notes:
  required:
  rowwise: no
  type: string
- column: CollectionType
  neotoma: ndb.collectionunits.colltypeid
  notes:
  required:
  rowwise: no
  type: string
- column: CollectionDevice
  neotoma: ndb.collectionunits.colldevice
  notes:
  required:
  rowwise: no
  type: string
- column: CollectionDate
  neotoma: db.collectionunits.colldate
  notes:
  required:
  rowwise: no
  type: string
- column: CUNotes
  neotoma: ndb.collectionunits.notes
  notes:
  required:
  rowwise: no
  type: string
- column: DepositionalEnvironment
  neotoma: ndb.collectionunits.depenvtid
  notes:
  required:
  rowwise: no
  type: string
- column: WaterDepth
  neotoma: ndb.collectionunits.waterdepth
  notes:
  required:
  rowwise: no
  type: float
- column: Location
  neotoma: ndb.collectionunits.location
  notes:
  required:
  rowwise: no
  type: string
- column: GPSLat
  neotoma: ndb.collectionunits.geog.latitude
  notes:
  required:
  rowwise: no
  type: float
- column: GPSLong
  neotoma: ndb.collectionunits.geog.longitude
  notes:
  required:
  rowwise: no
  type: float
- column: GPSError
  neotoma: ndb.collectionunits.gpserror
  notes:
  required:
  rowwise: no
  type: float
- column: GPSAltitude
  neotoma: ndb.collectionunits.gpsaltitude
  notes:
  required:
  rowwise: no
  type: float
- column: Substrate
  neotoma: ndb.collectionunits.substrateid
  notes:
  required:
  rowwise: no
  type: string
- column: SlopeAngle
  neotoma: ndb.collectionunits.slopeangle
  notes:
  required:
  rowwise: no
  type: float
- column: SlopeAspect
  neotoma: ndb.collectionunits.slopeaspect
  notes:
  required:
  rowwise: no
  type: float
- column: Collectors_ID
  neotoma: ndb.collectors.contactid
  notes:
  required:
  rowwise: no
  type: string
- column: Collectors_Names
  neotoma: ndb.collectors.contactname
  notes:
  required:
  rowwise: no
  type: string
- column: Method
  neotoma: ndb.geochronology.geochrontypeid
  notes:
  required:
  rowwise: true
  type: string
- column: chronmethod
  neotoma: ndb.chroncontrols.chroncontroltypeid
  notes:
  required:
  rowwise: true
  type: string
- column: AgeUnits_Sample
  neotoma: ndb.chroncontrols.agetypeid
  notes:
  required:
  rowwise: true
  type: string
- column: AgeUnits_Sample
  neotoma: ndb.geochronology.agetypeid
  notes:
  required:
  rowwise: no
  type: string
- column: SampleAge
  neotoma: ndb.chroncontrols.age
  notes:
  required:
  rowwise: true
  type: float
#- column: AgeUnits_Sample
#  neotoma: ndb.sampleages.agetype
#  notes:
#  required:
#  rowwise: no
#  type: string
- column: geochron_depth
  neotoma: ndb.chroncontrols.depth
  notes:
  required:
  rowwise: true
  type: float
- column: geochron_depth
  neotoma: ndb.analysisunits.depth
  notes:
  required:
  rowwise: true
  type: float
- column: Thickness
  neotoma: ndb.chroncontrols.thickness
  notes:
  required:
  rowwise: true
  type: float
- column: LabNumber
  neotoma: ndb.geochronology.labnumber
  notes:
  required:
  rowwise: true
  type: string
- column: SampleAge
  neotoma: ndb.geochronology.age
  notes:
  required:
  rowwise: true
  type: float
- column: SampleID
  neotoma: _link_chroncontrol
  link_id: chroncontrol
  required: true
  rowwise: true
  type: int
- column: OlderSampleAge
  neotoma: ndb.chroncontrols.agelimitolder
  notes:
  required:
  rowwise: true
  type: float
- column: ErrorOlder
  neotoma: ndb.geochronology.errorolder
  notes:
  required:
  rowwise: true
  type: float
- column: ErrorYounger
  neotoma: ndb.geochronology.erroryounger
  notes:
  required:
  rowwise: true
  type: float
- column: YoungerSampleAge
  neotoma: ndb.chroncontrols.agelimityounger
  notes:
  required:
  rowwise: true
  type: float
- column: MaterialDated
  neotoma: ndb.geochronology.materialdated
  notes:
  required:
  rowwise: true
  type: string
- column: SampleNotes
  neotoma: ndb.geochronology.notes
  notes:
  required:
  rowwise: true
  type: string
- column: SampleNotes
  neotoma: ndb.chroncontrols.notes
  notes:
  required:
  rowwise: true
  type: string
- column: Investigators_geochron_neoID
  neotoma: ndb.chronologies.contactid
  notes:
  required:
  rowwise: no
  type: string
  chronologyname: Temoltzin-Loranca et al. (2023)
#- column: OlderSampleAge
#  neotoma: ndb.sampleages.ageolder
#  notes:
#  required:
#  rowwise: true
#  type: float
- column: NeotomaContactID
  neotoma: ndb.contacts.contactid
  notes:
  required:
  rowwise: no
  type: string
- column: NeotomaAliasID
  neotoma: ndb.contacts.contactid
  notes:
  required:
  rowwise: no
  type: string
- column: FullContactName
  neotoma: ndb.contacts.contactname
  notes:
  required:
  rowwise: no
  type: string
- column: FamilyName
  neotoma: ndb.contacts.familyname
  notes:
  required:
  rowwise: no
  type: string
- column: GivenNames
  neotoma: ndb.contacts.givennames
  notes:
  required:
  rowwise: no
  type: string
- column: LeadingInitials
  neotoma: ndb.contacts.leadinginitials
  notes:
  required:
  rowwise: no
  type: string
- column: ContactTitle
  neotoma: ndb.contacts.title
  notes:
  required:
  rowwise: no
  type: string
- column: Address
  neotoma: ndb.contacts.address
  notes:
  required:
  rowwise: no
  type: string
- column: Email
  neotoma: ndb.contacts.email
  notes:
  required:
  rowwise: no
  type: string
- column: Telephone
  neotoma: ndb.contacts.phone
  notes:
  required:
  rowwise: no
  type: string
- column: PublicationType
  neotoma: ndb.publications.pubtypeid
  notes:
  required:
  rowwise: true
  type: string
- column: NeotomaID_pub
  neotoma: ndb.publications.publicationid
  notes:
  required:
  rowwise: true
  type: float
- column: DOI_pub
  neotoma: ndb.publications.doi
  notes:
  required:
  rowwise: true
  type: string
- column: PublicationYear
  neotoma: ndb.publications.year
  notes:
  required:
  rowwise: true
  type: float
- column: Citation
  neotoma: ndb.publications.citation
  notes:
  required:
  rowwise: true
  type: string
- column: Title
  neotoma: ndb.publications.articletitle
  notes:
  required:
  rowwise: true
  type: string
- column: Journal
  neotoma: ndb.publications.journal
  notes:
  required:
  rowwise: true
  type: string
- column: Volume
  neotoma: ndb.publications.volume
  notes:
  required:
  rowwise: true
  type: string
- column: Pages
  neotoma: ndb.publications.pages
  notes:
  required:
  rowwise: true
  type: string
- column: authorIDs
  neotoma: ndb.publicationauthors.contactid
  notes:
  required:
  rowwise: true
  type: string
- column: Processors_ID
  neotoma: ndb.datasetprocessor.contactid
  notes:
  required:
  rowwise: no
  type: string
- column: Investigators_ID
  neotoma: ndb.datasetpis.contactid
  notes:
  required:
  rowwise: no
  type: string
- column: Processors_Names
  neotoma: ndb.dataprocessors.contactname
  notes:
  required:
  rowwise: no
  type: string
- column: Investigators_Names
  neotoma: ndb.datasetpis.contactname
  notes:
  required:
  rowwise: no
  type: string
#- column: DatasetType
#  neotoma: ndb.datasets.datasettype
#  notes:
#  required:
#  rowwise: no
#  type: string
- column: Name
  neotoma: ndb.datasets.datasetname
  notes:
  required:
  value: LV2 pollen
  rowwise: no
  type: string
- column: ChronologyName
  neotoma: ndb.chronologies.chronologyname
  notes:
  required:
  rowwise: no
  type: string
  chronologyname: Temoltzin-Loranca et al. (2023)
- column: AgeUnits
  neotoma: ndb.chronologies.agetypeid
  notes:
  required:
  rowwise: no
  type: string
  chronologyname: Temoltzin-Loranca et al. (2023)
- column: Default
  neotoma: ndb.chronologies.isdefault
  notes:
  required:
  rowwise: no
  type: string
  chronologyname: Temoltzin-Loranca et al. (2023)
- column: DatePrepared
  neotoma: ndb.chronologies.dateprepared
  notes:
  required:
  rowwise: no
  type: float
  chronologyname: Temoltzin-Loranca et al. (2023)
- column: Model
  neotoma: ndb.chronologies.agemodel
  notes:
  required:
  rowwise: no
  type: string
- column: Model
  neotoma: ndb.sampleages.agemodel
  notes:
  required:
  rowwise: true
  type: string
  chronologyname: Temoltzin-Loranca et al. (2023)
- column: AgeBoundOlder
  neotoma: ndb.chronologies.ageboundolder
  notes:
  required:
  rowwise: no
  type: float
  chronologyname: Temoltzin-Loranca et al. (2023)
- column: AgeBoundYounger
  neotoma: ndb.chronologies.ageboundyounger
  notes:
  required:
  rowwise: no
  type: float
  chronologyname: Temoltzin-Loranca et al. (2023)
- column: AgeModelNotes
  neotoma: ndb.chronologies.notes
  notes:
  required:
  rowwise: no
  type: string
  chronologyname: Temoltzin-Loranca et al. (2023)
- column: PreparersContactID_neo
  neotoma: ndb.chronologies.contactid
  notes:
  required:
  rowwise: no
  type: string
  chronologyname: Temoltzin-Loranca et al. (2023)
#- column: Preparers_Name
#  neotoma: ndb.chronologies.contactname
#  notes:
#  required:
#  rowwise: no
#  type: string
#  chronologyname: Temoltzin-Loranca et al. (2023)
- column: SampAnalyst_neoID
  neotoma: ndb.sampleanalysts.contactid
  notes:
  required:
  rowwise: no
  type: string
- column: Samp.Analyst
  neotoma: ndb.sampleanalysts.contactname
  notes:
  required:
  rowwise: no
  type: string

