apiVersion: neotoma v2.0
headers: 2
kind: Development
metadata:
- column: datasettypeid
  neotoma: ndb.datasettypes.datasettype
  notes: null
  overwrite: false
  required: true
  value: pollen
- column: databaseid
  neotoma: 'ndb.datasetdatabases.databasename'
  notes: null
  overwrite: false
  required: true
  value: African Pollen Database
- column: Address
  neotoma: ndb.contacts.address
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Age
  neotoma: ndb.sampleages.age
  overwrite: false
  required: null
  rowwise: true
  type: float
- column: AgeBoundOlder
  neotoma: ndb.chronologies.ageboundolder
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: AgeBoundYounger
  neotoma: ndb.chronologies.ageboundyounger
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: AgeModelNotes
  neotoma: ndb.chronologies.notes
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: AgeUnits
  neotoma: ndb.chronologies.agetypeid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: AgeUnits_Sample
  neotoma: ndb.chroncontrols.agetypeid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Altitude
  neotoma: ndb.sites.altitude
  overwrite: false
  required: null
  rowwise: false
  type: int
- column: Area
  neotoma: ndb.sites.area
  overwrite: false
  required: null
  rowwise: false
  type: int
- column: CUNotes
  neotoma: ndb.collectionunits.notes
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: ChronologyName
  neotoma: ndb.chronologies.chronologyname
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Citation
  neotoma: ndb.publications.citation
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: CollectionDate
  neotoma: ndb.collectionunits.colldate
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: CollectionDevice
  neotoma: ndb.collectionunits.colldevice
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: CollectionName
  neotoma: ndb.collectionunits.collunitname
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: CollectionType
  neotoma: ndb.collectionunits.colltypeid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Collectors_ID
  neotoma: ndb.collectors.collectorid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: ContactTitle
  neotoma: ndb.contacts.title
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Country
  neotoma: ndb.geopoliticalunits.geopoliticalid
  notes: double check these fields
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: County
  neotoma: ndb.geopoliticalunits.geopoliticalid
  notes: double check these fields
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: DOI_pub
  neotoma: ndb.publications.doi
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: DatasetType
  neotoma: ndb.datasets.datasttypeid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: DatePrepared
  neotoma: ndb.chronologies.dateprepared
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Default
  neotoma: ndb.chronologies.isdefault
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: DepositionalEnvironment
  neotoma: ndb.collectionunits.depenvtid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Depth
  neotoma: ndb.chroncontrols.depth
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Email
  neotoma: ndb.contacts.email
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: ErrorOlder
  neotoma: ndb.geochronology.errorolder
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: ErrorYounger
  neotoma: ndb.geochronology.erroryounger
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: FamilyName
  neotoma: ndb.contacts.familyname
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Fax
  neotoma: ndb.contacts.fax
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: FullContactName
  neotoma: ndb.contacts.contactname
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: GPSAltitude
  neotoma: ndb.collectionunits.gpsaltitude
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: GPSError
  neotoma: ndb.collectionunits.gpserror
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: GPSLat
  neotoma: ndb.collectionunits.gpslatitude
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: GPSLong
  neotoma: ndb.collectionunits.gpslongitude
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: GivenNames
  neotoma: ndb.contacts.givennames
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Handle
  neotoma: ndb.collectionunits.handle
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Investigators
  neotoma: ndb.datasetpis.contactid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Investigators_geochron_neoID
  neotoma: ndb.chronologies.contactid
  notes: ??
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Journal
  neotoma: ndb.publications.journal
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: LabNumber
  neotoma: ndb.geochronology.labnumber
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: LatNorth
  neotoma: ndb.sites.geog.latitude #north
  overwrite: false
  required: null
  rowwise: false
  type: float
# - column: LatSouth
#   neotoma: ndb.sites.latitudesouth
#   overwrite: false
#   required: null
#   rowwise: false
#   type: float
- column: LeadingInitials
  neotoma: ndb.contacts.leadinginitials
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Location
  neotoma: ndb.collectionunits.location
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: LongEast
  neotoma: ndb.sites.geog.longitude #east
  overwrite: false
  required: null
  rowwise: false
  type: float
# - column: LongWest
#   neotoma: ndb.sites.longitudewest
#   overwrite: false
#   required: null
#   rowwise: false
#   type: float
- column: MaterialDated
  neotoma: ndb.geochronology.materialdated
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Method
  neotoma: ndb.geochronology.geochrontypeid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Model
  neotoma: ndb.chronologies.agemodel
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Name
  neotoma: ndb.datasets.datasetname
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: NeotomaAliasID
  neotoma: ndb.contacts.contactid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: NeotomaContactID
  neotoma: ndb.contacts.contactid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: NeotomaID_pub
  neotoma: ndb.publications.publicationid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Pages
  neotoma: ndb.publications.pages
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: PreparersContactID
  neotoma: ndb.chronologies.contactid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Processors
  neotoma: ndb.dataprocessors.contactid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: PublicationType
  neotoma: ndb.publications.pubtypeid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: PublicationYear
  neotoma: ndb.publications.year
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: SampleAge
  neotoma: ndb.chroncontrols.age
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: SampleNotes
  neotoma: ndb.geochronology.notes
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: SiteDescription
  neotoma: ndb.sites.sitedescription
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: SiteName
  neotoma: ndb.sites.sitename
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: SiteNotes
  neotoma: ndb.sites.notes
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: SlopeAngle
  neotoma: ndb.collectionunits.slopeangle
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: SlopeAspect
  neotoma: ndb.collectionunits.slopeaspect
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: State
  neotoma: ndb.geopoliticalunits.geopoliticalid
  notes: double check these fields
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Substrate
  neotoma: ndb.collectionunits.substrateid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Telephone
  neotoma: ndb.contacts.phone
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Thickness
  neotoma: ndb.chroncontrols.thickness
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Title
  neotoma: ndb.publications.articletitle
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: URL
  neotoma: ndb.contacts.url
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: Volume
  neotoma: ndb.publications.volume
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: WaterDepth
  neotoma: ndb.collectionunits.waterdepth
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: authorIDs
  neotoma: ndb.publicationauthors.contactid
  overwrite: false
  required: null
  rowwise: false
  type: string
- column: depths
  neotoma: ndb.analysisunits.depth
  overwrite: false
  required: null
  rowwise: true
  type: Float
- column: element
  neotoma: ndb.variableelements.elementtypeid
  overwrite: false
  required: null
  rowwise: true
  type: string
- column: value
  neotoma: ndb.data.value
  overwrite: false
  required: null
  rowwise: true
  type: float
- column: variablename
  neotoma: ndb.data.variableid
  overwrite: false
  required: null
  rowwise: true
  type: string
