SELECT ts.insertchronology(_collectionunitid := %(collunitid)s,
                               _agetypeid := %(agetype)s,
                               _contactid := %(contactid)s,
                               _isdefault := TRUE,
                               _chronologyname := %(chronologyname)s,
                               _dateprepared := %(dateprepared)s,
                               _agemodel := %(agemodel)s,
                               _ageboundyounger := %(maxage)s,
                               _ageboundolder := %(minage)s)