SELECT ts.insertsample(_analysisunitid := %(analysisunitid)s,
                                          _datasetid := %(datasetid)s,
                                          _samplename := %(samplename)s,
                                          _sampledate := %(sampledate)s,
                                          _analysisdate := %(analysisdate)s,
                                          _taxonid := %(taxonid)s,
                                          _labnumber := %(labnumber)s,
                                          _prepmethod := %(prepmethod)s,
                                          _notes := %(notes)s)